In [1]:
import numpy as np

In [2]:
np.__version__

'1.26.4'

In [3]:
import sys
sys.version

'3.12.4 | packaged by Anaconda, Inc. | (main, Jun 18 2024, 15:03:56) [MSC v.1929 64 bit (AMD64)]'

creating array

In [5]:
my_list = [0, 1, 2, 3, 4, 5]
my_list

[0, 1, 2, 3, 4, 5]

In [6]:
type(my_list)

list

In [7]:
arr = np.array(my_list) #converting list to array

In [8]:
arr

array([0, 1, 2, 3, 4, 5])

In [9]:
type(arr)

numpy.ndarray

In [10]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [11]:
np.arange(3.0)

array([0., 1., 2.])

In [12]:
np.arange(0,5)

array([0, 1, 2, 3, 4])

In [13]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [14]:
np.arange(20,10) #1st arg should be smaller than 2 nd arg

array([], dtype=int32)

In [15]:
np.arange(-20,10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7,   8,   9])

In [16]:
np.arange(-20,-10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11])

In [17]:
ar = np.arange(-30,20)
ar

array([-30, -29, -28, -27, -26, -25, -24, -23, -22, -21, -20, -19, -18,
       -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,  -7,  -6,  -5,
        -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,   6,   7,   8,
         9,  10,  11,  12,  13,  14,  15,  16,  17,  18,  19])

In [18]:
np.arange(10,10)

array([], dtype=int32)

In [19]:
np.arange(10,30,5)

array([10, 15, 20, 25])

In [20]:
np.arange(0,10,3)

array([0, 3, 6, 9])

In [21]:
np.zeros(3)

array([0., 0., 0.])

In [22]:
np.zeros(5,dtype = int)

array([0, 0, 0, 0, 0])

In [23]:
np.zeros((2,2),dtype = int)

array([[0, 0],
       [0, 0]])

In [24]:
zero = np.zeros([2,2])
print(zero)

print('####')
print(type(zero))

[[0. 0.]
 [0. 0.]]
####
<class 'numpy.ndarray'>


In [25]:
np.zeros([2,10], dtype = int)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [26]:
n = (6,7)
n1 = (6,8)
print(np.zeros(n))

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [27]:
np.ones(3)

array([1., 1., 1.])

In [28]:
np.ones(4, dtype = int)

array([1, 1, 1, 1])

In [29]:
range(5)

range(0, 5)

In [30]:
r = range(5) # creating a var to display the number range
r

range(0, 5)

In [31]:
for i in r:
    print(i)

0
1
2
3
4


In [32]:
list(range(5))

[0, 1, 2, 3, 4]

In [33]:
list(range(1,10, 3))

[1, 4, 7]

In [35]:
rand(3,2)

NameError: name 'rand' is not defined

In [37]:
rand(3,2)
random.rand(3,2)

NameError: name 'rand' is not defined

In [39]:
np.random.rand(5)

array([0.35602352, 0.45459548, 0.3989603 , 0.06721358, 0.16650458])

In [41]:
np.rand(4) #module is missing 

AttributeError: module 'numpy' has no attribute 'rand'

In [42]:
np.random.rand(2,4)

array([[0.56443676, 0.76760984, 0.97488039, 0.73245828],
       [0.02548278, 0.76299962, 0.28156614, 0.75832326]])

In [45]:
np.random.randint(2,4)

3

In [47]:
np.random.randint(2,20)

15

In [49]:
np.random.randint(0,1)

0

In [51]:
np.random.randint(10,20,3) #it will generate 3 random numbers

array([17, 13, 17])

In [53]:
np.random.randint(1,6,4)

array([1, 5, 3, 1])

In [55]:
np.random.randint(10,40,(10,10)) #create a array

array([[36, 34, 34, 26, 33, 10, 26, 23, 32, 29],
       [31, 27, 17, 39, 26, 12, 13, 39, 14, 27],
       [14, 30, 28, 27, 33, 14, 34, 34, 18, 11],
       [12, 25, 37, 39, 14, 33, 14, 15, 19, 30],
       [14, 21, 29, 14, 39, 21, 15, 35, 27, 27],
       [36, 26, 16, 21, 13, 22, 26, 18, 37, 15],
       [10, 19, 37, 33, 10, 27, 16, 15, 32, 28],
       [34, 34, 20, 29, 35, 21, 19, 39, 11, 34],
       [18, 32, 23, 29, 21, 10, 17, 12, 30, 24],
       [38, 27, 24, 18, 34, 37, 37, 24, 26, 28]])

In [57]:
b = np.random.randint(10,20,(5,4))
b

array([[13, 10, 16, 13],
       [19, 15, 14, 12],
       [19, 10, 14, 10],
       [12, 16, 12, 12],
       [18, 15, 15, 15]])

In [59]:
type(b)

numpy.ndarray

In [61]:
b[1:3] #slicing

array([[19, 15, 14, 12],
       [19, 10, 14, 10]])

In [63]:
b[1,2] # gives a specific element from the matrix

14

OPERATIONS

In [71]:
a = np.random.randint(10,20,5)
a

array([18, 13, 17, 19, 11])

In [73]:
id(a)

2340940906192

In [75]:
arr

array([0, 1, 2, 3, 4, 5])

In [79]:
arr2 = np.random.randint(0,100,(10,10))
arr2

array([[58, 86, 69, 61, 26, 17, 74, 58, 73, 63],
       [92, 38, 61, 78, 47, 93, 61, 26, 56, 50],
       [55, 27, 59, 15, 72, 40, 79, 42, 47, 82],
       [25, 66, 95, 99, 86, 51, 58, 11, 71, 28],
       [95, 19, 10, 93,  4, 12,  2, 41, 90, 80],
       [84, 22, 10, 85, 14, 54, 68,  8, 84, 20],
       [13, 59, 16,  6, 13, 99, 96, 99, 66, 35],
       [28, 88, 54, 38, 44, 45, 30, 68, 50, 32],
       [82, 12, 32, 50, 50,  2, 20, 70, 53,  1],
       [27, 23, 44, 74, 87, 98,  6, 89,  4, 31]])

In [81]:
arr.max()

5

In [83]:
arr.min()

0

In [85]:
arr.mean()

2.5

In [87]:
arr.median()

AttributeError: 'numpy.ndarray' object has no attribute 'median'

In [89]:
from numpy import *
a = array([1,2,3,4,9])
median(a)

3.0

Reshaping the array 

In [92]:
arr.reshape(3,2)

array([[0, 1],
       [2, 3],
       [4, 5]])

In [94]:
arr.reshape(6,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [98]:
arr.reshape(2,3,order = 'C')

array([[0, 1, 2],
       [3, 4, 5]])

In [100]:
arr.reshape(2,3,order = 'F')

array([[0, 2, 4],
       [1, 3, 5]])

In [102]:
arr.reshape(2,3,order = 'A')

array([[0, 1, 2],
       [3, 4, 5]])